name: Release FileBasket

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.7.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Get Commit Count
      id: commit_count
      shell: bash
      run: |
        COUNT=$(git rev-list --count HEAD)
        echo "BUILD_NUMBER=$COUNT" >> $GITHUB_ENV

    - name: Configure and Build
      run: |
        cmake -B build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release

    - name: Run windeployqt
      run: |
        windeployqt --no-compiler-runtime build/FileBasket.exe

    - name: Create Archive
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path release_pkg

        Copy-Item -Path "build/*" -Destination "release_pkg" -Recurse

        Compress-Archive -Path release_pkg/* -DestinationPath "FileBasket-win64.zip"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: FileBasket-win64.zip
        tag_name: ${{ env.BUILD_NUMBER }}
        name: Build ${{ env.BUILD_NUMBER }}
        body: |
          Release for commit #${{ env.BUILD_NUMBER }}.
          Changes: ${{ github.event.head_commit.message }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}